# BloodMNIST (8-class blood cell classification)
seed: 42
epochs: 200
batch_size: 128
rgb: true
lr: 0.0003
weight_decay: 0.0001
scheduler:
  name: cosine_warm_restarts
  T_0: 10
  T_mult: 2
label_smoothing: 0.1
data_root: ./data
num_classes: 8
